// Generated by Haxe 4.2.1
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_haxe_ds_List
#include <haxe/ds/List.h>
#endif
#ifndef INCLUDED_haxe_ds__List_ListNode
#include <haxe/ds/_List/ListNode.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_109688f3b41df45c_45_new,"haxe.ds.List","new",0x82be24e7,"haxe.ds.List.new","/usr/share/haxe/std/haxe/ds/List.hx",45,0xd0d1e26e)
HX_LOCAL_STACK_FRAME(_hx_pos_109688f3b41df45c_68_push,"haxe.ds.List","push",0xe500b373,"haxe.ds.List.push","/usr/share/haxe/std/haxe/ds/List.hx",68,0xd0d1e26e)
HX_LOCAL_STACK_FRAME(_hx_pos_109688f3b41df45c_177_toString,"haxe.ds.List","toString",0xaa41b2c5,"haxe.ds.List.toString","/usr/share/haxe/std/haxe/ds/List.hx",177,0xd0d1e26e)
static const ::String _hx_array_data_15aa2575_4[] = {
	HX_("{",7b,00,00,00),
};
static const ::String _hx_array_data_15aa2575_5[] = {
	HX_(", ",74,26,00,00),
};
static const ::String _hx_array_data_15aa2575_6[] = {
	HX_("}",7d,00,00,00),
};
namespace haxe{
namespace ds{

void List_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_109688f3b41df45c_45_new)
HXDLIN(  45)		this->length = 0;
            	}

Dynamic List_obj::__CreateEmpty() { return new List_obj; }

void *List_obj::_hx_vtable = 0;

Dynamic List_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< List_obj > _hx_result = new List_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool List_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x39a75d33;
}

void List_obj::push( ::Dynamic item){
            	HX_GC_STACKFRAME(&_hx_pos_109688f3b41df45c_68_push)
HXLINE(  69)		 ::haxe::ds::_List::ListNode x =  ::haxe::ds::_List::ListNode_obj::__alloc( HX_CTX ,item,this->h);
HXLINE(  70)		this->h = x;
HXLINE(  71)		if (::hx::IsNull( this->q )) {
HXLINE(  72)			this->q = x;
            		}
HXLINE(  73)		this->length++;
            	}


HX_DEFINE_DYNAMIC_FUNC1(List_obj,push,(void))

::String List_obj::toString(){
            	HX_GC_STACKFRAME(&_hx_pos_109688f3b41df45c_177_toString)
HXLINE( 178)		 ::StringBuf s =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 179)		bool first = true;
HXLINE( 180)		 ::haxe::ds::_List::ListNode l = this->h;
HXLINE( 181)		{
HXLINE( 181)			if (::hx::IsNotNull( s->charBuf )) {
HXLINE( 181)				s->flush();
            			}
HXDLIN( 181)			if (::hx::IsNull( s->b )) {
HXLINE( 181)				s->b = ::Array_obj< ::String >::fromData( _hx_array_data_15aa2575_4,1);
            			}
            			else {
HXLINE( 181)				s->b->push(HX_("{",7b,00,00,00));
            			}
            		}
HXLINE( 182)		while(::hx::IsNotNull( l )){
HXLINE( 183)			if (first) {
HXLINE( 184)				first = false;
            			}
            			else {
HXLINE( 186)				if (::hx::IsNotNull( s->charBuf )) {
HXLINE( 186)					s->flush();
            				}
HXDLIN( 186)				if (::hx::IsNull( s->b )) {
HXLINE( 186)					s->b = ::Array_obj< ::String >::fromData( _hx_array_data_15aa2575_5,1);
            				}
            				else {
HXLINE( 186)					s->b->push(HX_(", ",74,26,00,00));
            				}
            			}
HXLINE( 187)			{
HXLINE( 187)				::String x = ::Std_obj::string(l->item);
HXDLIN( 187)				if (::hx::IsNotNull( s->charBuf )) {
HXLINE( 187)					s->flush();
            				}
HXDLIN( 187)				if (::hx::IsNull( s->b )) {
HXLINE( 187)					s->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            				}
            				else {
HXLINE( 187)					::Array< ::String > s1 = s->b;
HXDLIN( 187)					s1->push(::Std_obj::string(x));
            				}
            			}
HXLINE( 188)			l = l->next;
            		}
HXLINE( 190)		{
HXLINE( 190)			if (::hx::IsNotNull( s->charBuf )) {
HXLINE( 190)				s->flush();
            			}
HXDLIN( 190)			if (::hx::IsNull( s->b )) {
HXLINE( 190)				s->b = ::Array_obj< ::String >::fromData( _hx_array_data_15aa2575_6,1);
            			}
            			else {
HXLINE( 190)				s->b->push(HX_("}",7d,00,00,00));
            			}
            		}
HXLINE( 191)		return s->toString();
            	}


HX_DEFINE_DYNAMIC_FUNC0(List_obj,toString,return )


::hx::ObjectPtr< List_obj > List_obj::__new() {
	::hx::ObjectPtr< List_obj > __this = new List_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< List_obj > List_obj::__alloc(::hx::Ctx *_hx_ctx) {
	List_obj *__this = (List_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(List_obj), true, "haxe.ds.List"));
	*(void **)__this = List_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

List_obj::List_obj()
{
}

void List_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(List);
	HX_MARK_MEMBER_NAME(h,"h");
	HX_MARK_MEMBER_NAME(q,"q");
	HX_MARK_MEMBER_NAME(length,"length");
	HX_MARK_END_CLASS();
}

void List_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(h,"h");
	HX_VISIT_MEMBER_NAME(q,"q");
	HX_VISIT_MEMBER_NAME(length,"length");
}

::hx::Val List_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"h") ) { return ::hx::Val( h ); }
		if (HX_FIELD_EQ(inName,"q") ) { return ::hx::Val( q ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"push") ) { return ::hx::Val( push_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"length") ) { return ::hx::Val( length ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"toString") ) { return ::hx::Val( toString_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val List_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"h") ) { h=inValue.Cast<  ::haxe::ds::_List::ListNode >(); return inValue; }
		if (HX_FIELD_EQ(inName,"q") ) { q=inValue.Cast<  ::haxe::ds::_List::ListNode >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"length") ) { length=inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void List_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("h",68,00,00,00));
	outFields->push(HX_("q",71,00,00,00));
	outFields->push(HX_("length",e6,94,07,9f));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo List_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::ds::_List::ListNode */ ,(int)offsetof(List_obj,h),HX_("h",68,00,00,00)},
	{::hx::fsObject /*  ::haxe::ds::_List::ListNode */ ,(int)offsetof(List_obj,q),HX_("q",71,00,00,00)},
	{::hx::fsInt,(int)offsetof(List_obj,length),HX_("length",e6,94,07,9f)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *List_obj_sStaticStorageInfo = 0;
#endif

static ::String List_obj_sMemberFields[] = {
	HX_("h",68,00,00,00),
	HX_("q",71,00,00,00),
	HX_("length",e6,94,07,9f),
	HX_("push",da,11,61,4a),
	HX_("toString",ac,d0,6e,38),
	::String(null()) };

::hx::Class List_obj::__mClass;

void List_obj::__register()
{
	List_obj _hx_dummy;
	List_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.ds.List",75,25,aa,15);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(List_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< List_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = List_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = List_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace haxe
} // end namespace ds
