// Generated by Haxe 4.2.1
#include <hxcpp.h>

#ifndef INCLUDED_haxe_io_Error
#include <haxe/io/Error.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_haxe_StackItem
#include <haxe/StackItem.h>
#endif
#ifndef INCLUDED_sys_thread__Thread_HaxeThread
#include <sys/thread/_Thread/HaxeThread.h>
#endif
#ifndef INCLUDED_sys_net_Host
#include <sys/net/Host.h>
#endif
#ifndef INCLUDED_markdown_InlineParser
#include <markdown/InlineParser.h>
#endif
#ifndef INCLUDED_markdown_ImgSyntax
#include <markdown/ImgSyntax.h>
#endif
#ifndef INCLUDED_markdown_LinkSyntax
#include <markdown/LinkSyntax.h>
#endif
#ifndef INCLUDED_markdown_HtmlRenderer
#include <markdown/HtmlRenderer.h>
#endif
#ifndef INCLUDED_markdown_TableSyntax
#include <markdown/TableSyntax.h>
#endif
#ifndef INCLUDED_markdown_BlockSyntax
#include <markdown/BlockSyntax.h>
#endif
#ifndef INCLUDED_haxe_SysTools
#include <haxe/SysTools.h>
#endif
#ifndef INCLUDED_Main
#include <Main.h>
#endif
#ifndef INCLUDED_DateTools
#include <DateTools.h>
#endif
#ifndef INCLUDED_sys_thread__Thread_Thread_Impl_
#include <sys/thread/_Thread/Thread_Impl_.h>
#endif
#ifndef INCLUDED_sys_thread_Mutex
#include <sys/thread/Mutex.h>
#endif
#ifndef INCLUDED_sys_thread_Lock
#include <sys/thread/Lock.h>
#endif
#ifndef INCLUDED_sys_thread__EventLoop_RegularEvent
#include <sys/thread/_EventLoop/RegularEvent.h>
#endif
#ifndef INCLUDED_sys_thread_EventLoop
#include <sys/thread/EventLoop.h>
#endif
#ifndef INCLUDED_sys_net_Socket
#include <sys/net/Socket.h>
#endif
#ifndef INCLUDED_sys_net__Socket_SocketOutput
#include <sys/net/_Socket/SocketOutput.h>
#endif
#ifndef INCLUDED_sys_net__Socket_SocketInput
#include <sys/net/_Socket/SocketInput.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif
#ifndef INCLUDED_sys_FileSystem
#include <sys/FileSystem.h>
#endif
#ifndef INCLUDED_markdown_TagState
#include <markdown/TagState.h>
#endif
#ifndef INCLUDED_markdown_CodeSyntax
#include <markdown/CodeSyntax.h>
#endif
#ifndef INCLUDED_markdown_TagSyntax
#include <markdown/TagSyntax.h>
#endif
#ifndef INCLUDED_markdown_AutolinkSyntax
#include <markdown/AutolinkSyntax.h>
#endif
#ifndef INCLUDED_markdown_TextSyntax
#include <markdown/TextSyntax.h>
#endif
#ifndef INCLUDED_markdown_AutolinkSyntaxWithoutBrackets
#include <markdown/AutolinkSyntaxWithoutBrackets.h>
#endif
#ifndef INCLUDED_markdown_InlineSyntax
#include <markdown/InlineSyntax.h>
#endif
#ifndef INCLUDED_markdown_OrderedListSyntax
#include <markdown/OrderedListSyntax.h>
#endif
#ifndef INCLUDED_markdown_UnorderedListSyntax
#include <markdown/UnorderedListSyntax.h>
#endif
#ifndef INCLUDED_markdown_ListSyntax
#include <markdown/ListSyntax.h>
#endif
#ifndef INCLUDED_markdown_ParagraphSyntax
#include <markdown/ParagraphSyntax.h>
#endif
#ifndef INCLUDED_markdown_ListItem
#include <markdown/ListItem.h>
#endif
#ifndef INCLUDED_markdown_BlockHtmlSyntax
#include <markdown/BlockHtmlSyntax.h>
#endif
#ifndef INCLUDED_markdown_HorizontalRuleSyntax
#include <markdown/HorizontalRuleSyntax.h>
#endif
#ifndef INCLUDED_markdown_GitHubCodeBlockSyntax
#include <markdown/GitHubCodeBlockSyntax.h>
#endif
#ifndef INCLUDED_markdown_CodeBlockSyntax
#include <markdown/CodeBlockSyntax.h>
#endif
#ifndef INCLUDED_markdown_BlockquoteSyntax
#include <markdown/BlockquoteSyntax.h>
#endif
#ifndef INCLUDED_markdown_HeaderSyntax
#include <markdown/HeaderSyntax.h>
#endif
#ifndef INCLUDED_markdown_SetextHeaderSyntax
#include <markdown/SetextHeaderSyntax.h>
#endif
#ifndef INCLUDED_markdown_EmptyBlockSyntax
#include <markdown/EmptyBlockSyntax.h>
#endif
#ifndef INCLUDED_markdown_BlockParser
#include <markdown/BlockParser.h>
#endif
#ifndef INCLUDED_markdown_TextNode
#include <markdown/TextNode.h>
#endif
#ifndef INCLUDED_markdown_ElementNode
#include <markdown/ElementNode.h>
#endif
#ifndef INCLUDED_markdown_NodeVisitor
#include <markdown/NodeVisitor.h>
#endif
#ifndef INCLUDED_markdown_Node
#include <markdown/Node.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_io_Path
#include <haxe/io/Path.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_haxe_io_Input
#include <haxe/io/Input.h>
#endif
#ifndef INCLUDED_haxe_io_Eof
#include <haxe/io/Eof.h>
#endif
#ifndef INCLUDED_haxe_io_BytesBuffer
#include <haxe/io/BytesBuffer.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_exceptions_NotImplementedException
#include <haxe/exceptions/NotImplementedException.h>
#endif
#ifndef INCLUDED_haxe_exceptions_PosException
#include <haxe/exceptions/PosException.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds__List_ListNode
#include <haxe/ds/_List/ListNode.h>
#endif
#ifndef INCLUDED_haxe_ValueException
#include <haxe/ValueException.h>
#endif
#ifndef INCLUDED_haxe_NativeStackTrace
#include <haxe/NativeStackTrace.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe__CallStack_CallStack_Impl_
#include <haxe/_CallStack/CallStack_Impl_.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_Link
#include <Link.h>
#endif
#ifndef INCLUDED_Document
#include <Document.h>
#endif
#ifndef INCLUDED_Markdown
#include <Markdown.h>
#endif
#ifndef INCLUDED_Page
#include <Page.h>
#endif
#ifndef INCLUDED_PageRoute
#include <PageRoute.h>
#endif
#ifndef INCLUDED_haxe_ds_List
#include <haxe/ds/List.h>
#endif
#ifndef INCLUDED_EReg
#include <EReg.h>
#endif
#ifndef INCLUDED_Date
#include <Date.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::io::Error_obj::__register();
::haxe::io::Encoding_obj::__register();
::haxe::StackItem_obj::__register();
::sys::thread::_Thread::HaxeThread_obj::__register();
::sys::net::Host_obj::__register();
::markdown::InlineParser_obj::__register();
::markdown::ImgSyntax_obj::__register();
::markdown::LinkSyntax_obj::__register();
::markdown::HtmlRenderer_obj::__register();
::markdown::TableSyntax_obj::__register();
::markdown::BlockSyntax_obj::__register();
::haxe::SysTools_obj::__register();
::Main_obj::__register();
::DateTools_obj::__register();
::sys::thread::_Thread::Thread_Impl__obj::__register();
::sys::thread::Mutex_obj::__register();
::sys::thread::Lock_obj::__register();
::sys::thread::_EventLoop::RegularEvent_obj::__register();
::sys::thread::EventLoop_obj::__register();
::sys::net::Socket_obj::__register();
::sys::net::_Socket::SocketOutput_obj::__register();
::sys::net::_Socket::SocketInput_obj::__register();
::sys::io::File_obj::__register();
::sys::FileSystem_obj::__register();
::markdown::TagState_obj::__register();
::markdown::CodeSyntax_obj::__register();
::markdown::TagSyntax_obj::__register();
::markdown::AutolinkSyntax_obj::__register();
::markdown::TextSyntax_obj::__register();
::markdown::AutolinkSyntaxWithoutBrackets_obj::__register();
::markdown::InlineSyntax_obj::__register();
::markdown::OrderedListSyntax_obj::__register();
::markdown::UnorderedListSyntax_obj::__register();
::markdown::ListSyntax_obj::__register();
::markdown::ParagraphSyntax_obj::__register();
::markdown::ListItem_obj::__register();
::markdown::BlockHtmlSyntax_obj::__register();
::markdown::HorizontalRuleSyntax_obj::__register();
::markdown::GitHubCodeBlockSyntax_obj::__register();
::markdown::CodeBlockSyntax_obj::__register();
::markdown::BlockquoteSyntax_obj::__register();
::markdown::HeaderSyntax_obj::__register();
::markdown::SetextHeaderSyntax_obj::__register();
::markdown::EmptyBlockSyntax_obj::__register();
::markdown::BlockParser_obj::__register();
::markdown::TextNode_obj::__register();
::markdown::ElementNode_obj::__register();
::markdown::NodeVisitor_obj::__register();
::markdown::Node_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::io::Path_obj::__register();
::haxe::io::Output_obj::__register();
::haxe::io::Input_obj::__register();
::haxe::io::Eof_obj::__register();
::haxe::io::BytesBuffer_obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::exceptions::NotImplementedException_obj::__register();
::haxe::exceptions::PosException_obj::__register();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::_List::ListNode_obj::__register();
::haxe::ValueException_obj::__register();
::haxe::NativeStackTrace_obj::__register();
::haxe::Exception_obj::__register();
::haxe::IMap_obj::__register();
::haxe::_CallStack::CallStack_Impl__obj::__register();
::Type_obj::__register();
::Sys_obj::__register();
::StringTools_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::Link_obj::__register();
::Document_obj::__register();
::Markdown_obj::__register();
::Page_obj::__register();
::PageRoute_obj::__register();
::haxe::ds::List_obj::__register();
::EReg_obj::__register();
::Date_obj::__register();
::haxe::io::Error_obj::__boot();
::haxe::io::Encoding_obj::__boot();
::haxe::StackItem_obj::__boot();
::sys::net::Host_obj::__init__();
::sys::thread::_Thread::HaxeThread_obj::__init__();
::DateTools_obj::__boot();
::Main_obj::__boot();
::haxe::SysTools_obj::__boot();
::markdown::BlockSyntax_obj::__boot();
::markdown::TableSyntax_obj::__boot();
::markdown::HtmlRenderer_obj::__boot();
::markdown::LinkSyntax_obj::__boot();
::markdown::ImgSyntax_obj::__boot();
::markdown::InlineParser_obj::__boot();
::sys::net::Host_obj::__boot();
::sys::thread::_Thread::HaxeThread_obj::__boot();
}

