// Generated by Haxe 4.2.1
#include <hxcpp.h>

#ifndef INCLUDED_95f339a1d026d52c
#define INCLUDED_95f339a1d026d52c
#include "hxMath.h"
#endif
#ifndef INCLUDED_Console
#include <Console.h>
#endif
#ifndef INCLUDED_EReg
#include <EReg.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED__Console_FormatFlag_Impl_
#include <_Console/FormatFlag_Impl_.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_haxe_io_Input
#include <haxe/io/Input.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_haxe_macro_Binop
#include <haxe/macro/Binop.h>
#endif
#ifndef INCLUDED_haxe_macro_Constant
#include <haxe/macro/Constant.h>
#endif
#ifndef INCLUDED_haxe_macro_ExprDef
#include <haxe/macro/ExprDef.h>
#endif
#ifndef INCLUDED_haxe_macro_StringLiteralKind
#include <haxe/macro/StringLiteralKind.h>
#endif
#ifndef INCLUDED_sys_io_Process
#include <sys/io/Process.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_91_printlnFormatted,"Console","printlnFormatted",0x76b51424,"Console.printlnFormatted","Console.hx",91,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_95_println,"Console","println",0xed13ffb8,"Console.println","Console.hx",95,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_153_printFormatted,"Console","printFormatted",0xb0f15c66,"Console.printFormatted","Console.hx",153,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_126_printFormatted,"Console","printFormatted",0xb0f15c66,"Console.printFormatted","Console.hx",126,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_257_print,"Console","print",0xb149c7b6,"Console.print","Console.hx",257,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_305_getAsciiFormat,"Console","getAsciiFormat",0x482bc9c9,"Console.getAsciiFormat","Console.hx",305,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_378_rgbToAscii256,"Console","rgbToAscii256",0x525d04f3,"Console.rgbToAscii256","Console.hx",378,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_375_rgbToAscii256,"Console","rgbToAscii256",0x525d04f3,"Console.rgbToAscii256","Console.hx",375,0xdfc4cbe7)
static const int _hx_array_data_e6271337_14[] = {
	(int)0,(int)95,(int)135,(int)175,(int)215,(int)255,
};
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_422_getBrowserFormat,"Console","getBrowserFormat",0x562471a0,"Console.getBrowserFormat","Console.hx",422,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_489_determineConsoleFormatMode,"Console","determineConsoleFormatMode",0x563fe535,"Console.determineConsoleFormatMode","Console.hx",489,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_561_joinArgs,"Console","joinArgs",0x8ecb567e,"Console.joinArgs","Console.hx",561,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_585_exec,"Console","exec",0xf1818828,"Console.exec","Console.hx",585,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_13_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",13,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_15_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",15,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_16_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",16,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_17_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",17,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_18_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",18,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_19_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",19,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_24_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",24,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_26_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",26,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_27_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",27,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_28_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",28,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_9b0ca03e92855c49_109_boot,"Console","boot",0xef7f18c9,"Console.boot","Console.hx",109,0xdfc4cbe7)

	#if defined(HX_WINDOWS)
	#include <windows.h>
	#endif


void Console_obj::__construct() { }

Dynamic Console_obj::__CreateEmpty() { return new Console_obj; }

void *Console_obj::_hx_vtable = 0;

Dynamic Console_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Console_obj > _hx_result = new Console_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Console_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x1aa204e7;
}

int Console_obj::formatMode;

::String Console_obj::logPrefix;

::String Console_obj::warnPrefix;

::String Console_obj::errorPrefix;

::String Console_obj::successPrefix;

::String Console_obj::debugPrefix;

 ::Dynamic Console_obj::printIntercept;

::String Console_obj::argSeparator;

int Console_obj::unicodeCompatibilityMode;

bool Console_obj::unicodeCompatibilityEnabled;

void Console_obj::printlnFormatted(::String s,::hx::Null< int >  __o_outputStream){
            		int outputStream = __o_outputStream.Default(0);
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_91_printlnFormatted)
HXDLIN(  91)		::Console_obj::printFormatted((s + HX_("\n",0a,00,00,00)),outputStream);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Console_obj,printlnFormatted,(void))

void Console_obj::println(::String s,::hx::Null< int >  __o_outputStream){
            		int outputStream = __o_outputStream.Default(0);
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_95_println)
HXDLIN(  95)		::Console_obj::print((s + HX_("\n",0a,00,00,00)),outputStream);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Console_obj,println,(void))

 ::EReg Console_obj::formatTagPattern;

void Console_obj::printFormatted(::String s,::hx::Null< int >  __o_outputStream){
            		HX_BEGIN_LOCAL_FUNC_S2(::hx::LocalFunc,_hx_Closure_0,::Array< ::Dynamic>,groupedProceedingTags,::Array< ::Dynamic>,activeFormatFlagStack) HXARGC(1)
            		::String _hx_run( ::EReg e){
            			HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_153_printFormatted)
HXLINE( 154)			bool open = ::hx::IsNull( e->matched(1) );
HXLINE( 155)			::Array< ::String > tags = e->matched(2).split(HX_(",",2c,00,00,00));
HXLINE( 158)			bool result;
HXDLIN( 158)			if (!(open)) {
HXLINE( 158)				result = (tags->length == 1);
            			}
            			else {
HXLINE( 158)				result = false;
            			}
HXDLIN( 158)			if (result) {
HXLINE( 159)				if ((tags->__get(0) == HX_("",00,00,00,00))) {
HXLINE( 161)					::String last = activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->__get((activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->length - 1));
HXLINE( 162)					{
HXLINE( 162)						int i = activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->indexOf(last,null());
HXDLIN( 162)						if ((i != -1)) {
HXLINE( 162)							int proceedingTags = groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->__get(i);
HXDLIN( 162)							activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->removeRange((i - proceedingTags),(proceedingTags + 1));
HXDLIN( 162)							groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->removeRange((i - proceedingTags),(proceedingTags + 1));
            						}
            					}
            				}
            				else {
HXLINE( 163)					if ((::_Console::FormatFlag_Impl__obj::fromString(tags->__get(0)) == HX_("reset",cf,49,c8,e6))) {
HXLINE( 149)						activeFormatFlagStack[0] = ::Array_obj< ::String >::__new(0);
HXLINE( 150)						groupedProceedingTags[0] = ::Array_obj< int >::__new(0);
            					}
            					else {
HXLINE( 167)						::String flag = ::_Console::FormatFlag_Impl__obj::fromString(tags->__get(0));
HXLINE( 168)						if (::hx::IsNotNull( flag )) {
HXLINE( 169)							int i = activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->indexOf(flag,null());
HXDLIN( 169)							if ((i != -1)) {
HXLINE( 169)								int proceedingTags = groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->__get(i);
HXDLIN( 169)								activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->removeRange((i - proceedingTags),(proceedingTags + 1));
HXDLIN( 169)								groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->removeRange((i - proceedingTags),(proceedingTags + 1));
            							}
            						}
            					}
            				}
            			}
            			else {
HXLINE( 173)				int proceedingTags = 0;
HXLINE( 174)				{
HXLINE( 174)					int _g = 0;
HXDLIN( 174)					while((_g < tags->length)){
HXLINE( 174)						::String tag = tags->__get(_g);
HXDLIN( 174)						_g = (_g + 1);
HXLINE( 175)						::String flag = ::_Console::FormatFlag_Impl__obj::fromString(tag);
HXLINE( 176)						if (::hx::IsNull( flag )) {
HXLINE( 176)							return e->matched(0);
            						}
HXLINE( 177)						if (open) {
HXLINE( 178)							{
HXLINE( 178)								activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->push(flag);
HXDLIN( 178)								groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->push(proceedingTags);
            							}
HXLINE( 179)							proceedingTags = (proceedingTags + 1);
            						}
            						else {
HXLINE( 181)							int i = activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->indexOf(flag,null());
HXDLIN( 181)							if ((i != -1)) {
HXLINE( 181)								int proceedingTags = groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->__get(i);
HXDLIN( 181)								activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->removeRange((i - proceedingTags),(proceedingTags + 1));
HXDLIN( 181)								groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->removeRange((i - proceedingTags),(proceedingTags + 1));
            							}
            						}
            					}
            				}
            			}
HXLINE( 187)			switch((int)(::Console_obj::formatMode)){
            				case (int)0: {
HXLINE( 191)					if (open) {
HXLINE( 192)						if ((activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->length > 0)) {
HXLINE( 193)							int lastFlagCount = (groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->__get((groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->length - 1)) + 1);
HXLINE( 194)							::String asciiFormatString = HX_("",00,00,00,00);
HXLINE( 195)							{
HXLINE( 195)								int _g = 0;
HXDLIN( 195)								int _g1 = lastFlagCount;
HXDLIN( 195)								while((_g < _g1)){
HXLINE( 195)									_g = (_g + 1);
HXDLIN( 195)									int i = (_g - 1);
HXLINE( 196)									int idx = ((groupedProceedingTags->__get(0).StaticCast< ::Array< int > >()->length - 1) - i);
HXLINE( 197)									asciiFormatString = (asciiFormatString + ::Console_obj::getAsciiFormat(activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->__get(idx)));
            								}
            							}
HXLINE( 199)							return asciiFormatString;
            						}
            						else {
HXLINE( 201)							return HX_("",00,00,00,00);
            						}
            					}
            					else {
HXLINE( 205)						::String result = ::Console_obj::getAsciiFormat(HX_("reset",cf,49,c8,e6));
HXLINE( 206)						::Array< ::String > result1 = ::Array_obj< ::String >::__new(activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->length);
HXDLIN( 206)						{
HXLINE( 206)							int _g = 0;
HXDLIN( 206)							int _g1 = activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >()->length;
HXDLIN( 206)							while((_g < _g1)){
HXLINE( 206)								_g = (_g + 1);
HXDLIN( 206)								int i = (_g - 1);
HXDLIN( 206)								{
HXLINE( 206)									::String inValue = ::Console_obj::getAsciiFormat(( (::String)(_hx_array_unsafe_get(activeFormatFlagStack->__get(0).StaticCast< ::Array< ::String > >(),i)) ));
HXDLIN( 206)									result1->__unsafe_set(i,inValue);
            								}
            							}
            						}
HXDLIN( 206)						::Array< ::String > _g2 = ::Array_obj< ::String >::__new(0);
HXDLIN( 206)						{
HXLINE( 206)							int _g3 = 0;
HXDLIN( 206)							::Array< ::String > _g4 = result1;
HXDLIN( 206)							while((_g3 < _g4->length)){
HXLINE( 206)								::String v = _g4->__get(_g3);
HXDLIN( 206)								_g3 = (_g3 + 1);
HXDLIN( 206)								if (::hx::IsNotNull( v )) {
HXLINE( 206)									_g2->push(v);
            								}
            							}
            						}
HXLINE( 204)						return (result + _g2->join(HX_("",00,00,00,00)));
            					}
            				}
            				break;
            				case (int)2: {
HXLINE( 221)					return HX_("",00,00,00,00);
            				}
            				break;
            			}
HXLINE( 187)			return null();
            		}
            		HX_END_LOCAL_FUNC1(return)

            		int outputStream = __o_outputStream.Default(0);
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_126_printFormatted)
HXLINE( 127)		s = (s + HX_("<//>",62,a0,cc,27));
HXLINE( 129)		::Array< ::Dynamic> activeFormatFlagStack = ::Array_obj< ::Dynamic>::__new(1)->init(0,::Array_obj< ::String >::__new());
HXLINE( 130)		::Array< ::Dynamic> groupedProceedingTags = ::Array_obj< ::Dynamic>::__new(1)->init(0,::Array_obj< int >::__new());
HXLINE( 153)		::String result = ::Console_obj::formatTagPattern->map(s, ::Dynamic(new _hx_Closure_0(groupedProceedingTags,activeFormatFlagStack)));
HXLINE( 251)		::Console_obj::print(result,outputStream);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Console_obj,printFormatted,(void))

void Console_obj::print(::String s,::hx::Null< int >  __o_outputStream){
            		int outputStream = __o_outputStream.Default(0);
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_257_print)
HXLINE( 260)		if (::hx::IsNotNull( ::Console_obj::printIntercept )) {
HXLINE( 261)			bool allowDefaultPrint = ( (bool)(::Console_obj::printIntercept(s,outputStream)) );
HXLINE( 262)			if (!(allowDefaultPrint)) {
HXLINE( 263)				return;
            			}
            		}
HXLINE( 272)		bool _hx_tmp;
HXDLIN( 272)		if ((::Console_obj::unicodeCompatibilityMode == 1)) {
HXLINE( 272)			_hx_tmp = !(::Console_obj::unicodeCompatibilityEnabled);
            		}
            		else {
HXLINE( 272)			_hx_tmp = false;
            		}
HXDLIN( 272)		if (_hx_tmp) {
HXLINE( 273)			::Console_obj::exec(HX_("chcp 65001",44,de,00,65),null());
HXLINE( 274)			::Console_obj::unicodeCompatibilityEnabled = true;
            		}
HXLINE( 277)		switch((int)(outputStream)){
            			case (int)1: case (int)2: {
HXLINE( 281)				::Sys_obj::_hx_stderr()->writeString(s,null());
            			}
            			break;
            			case (int)0: case (int)3: {
HXLINE( 279)				::Sys_obj::_hx_stdout()->writeString(s,null());
            			}
            			break;
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Console_obj,print,(void))

::String Console_obj::getAsciiFormat(::String flag){
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_305_getAsciiFormat)
HXLINE( 307)		if ((flag.charAt(0) == HX_("#",23,00,00,00))) {
HXLINE( 308)			::String hex = flag.substr(1,null());
HXLINE( 309)			 ::Dynamic r = ::Std_obj::parseInt((HX_("0x",48,2a,00,00) + hex.substr(0,2)));
HXDLIN( 309)			 ::Dynamic g = ::Std_obj::parseInt((HX_("0x",48,2a,00,00) + hex.substr(2,2)));
HXDLIN( 309)			 ::Dynamic b = ::Std_obj::parseInt((HX_("0x",48,2a,00,00) + hex.substr(4,2)));
HXLINE( 310)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + ::Console_obj::rgbToAscii256(( (int)(r) ),( (int)(g) ),( (int)(b) ))) + HX_("m",6d,00,00,00));
            		}
HXLINE( 314)		if ((flag.substr(0,3) == HX_("bg#",be,b6,4a,00))) {
HXLINE( 315)			::String hex = flag.substr(3,null());
HXLINE( 316)			 ::Dynamic r = ::Std_obj::parseInt((HX_("0x",48,2a,00,00) + hex.substr(0,2)));
HXDLIN( 316)			 ::Dynamic g = ::Std_obj::parseInt((HX_("0x",48,2a,00,00) + hex.substr(2,2)));
HXDLIN( 316)			 ::Dynamic b = ::Std_obj::parseInt((HX_("0x",48,2a,00,00) + hex.substr(4,2)));
HXLINE( 317)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + ::Console_obj::rgbToAscii256(( (int)(r) ),( (int)(g) ),( (int)(b) ))) + HX_("m",6d,00,00,00));
            		}
HXLINE( 320)		::String _hx_switch_0 = flag;
            		if (  (_hx_switch_0==HX_("bg_black",85,94,4b,51)) ){
HXLINE( 348)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 0) + HX_("m",6d,00,00,00));
HXDLIN( 348)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_blue",94,fe,23,0e)) ){
HXLINE( 352)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 4) + HX_("m",6d,00,00,00));
HXDLIN( 352)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_cyan",1d,01,d7,0e)) ){
HXLINE( 354)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 6) + HX_("m",6d,00,00,00));
HXDLIN( 354)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_green",89,cd,46,36)) ){
HXLINE( 350)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 2) + HX_("m",6d,00,00,00));
HXDLIN( 350)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_black",9c,09,69,dd)) ){
HXLINE( 356)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 8) + HX_("m",6d,00,00,00));
HXDLIN( 356)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_blue",5d,f9,41,dc)) ){
HXLINE( 360)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 12) + HX_("m",6d,00,00,00));
HXDLIN( 360)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_cyan",e6,fb,f4,dc)) ){
HXLINE( 362)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 14) + HX_("m",6d,00,00,00));
HXDLIN( 362)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_green",a0,42,64,c2)) ){
HXLINE( 358)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 10) + HX_("m",6d,00,00,00));
HXDLIN( 358)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_magenta",46,5f,2f,aa)) ){
HXLINE( 361)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 13) + HX_("m",6d,00,00,00));
HXDLIN( 361)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_red",ee,6b,ce,2d)) ){
HXLINE( 357)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 9) + HX_("m",6d,00,00,00));
HXDLIN( 357)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_white",86,7e,34,f2)) ){
HXLINE( 363)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 15) + HX_("m",6d,00,00,00));
HXDLIN( 363)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_yellow",f7,cc,32,10)) ){
HXLINE( 359)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 11) + HX_("m",6d,00,00,00));
HXDLIN( 359)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_magenta",6f,36,f9,c3)) ){
HXLINE( 353)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 5) + HX_("m",6d,00,00,00));
HXDLIN( 353)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_red",97,3a,61,bc)) ){
HXLINE( 349)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 1) + HX_("m",6d,00,00,00));
HXDLIN( 349)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_white",6f,09,17,66)) ){
HXLINE( 355)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 7) + HX_("m",6d,00,00,00));
HXDLIN( 355)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bg_yellow",ee,cd,89,02)) ){
HXLINE( 351)			return ((HX_("\x1b""[48;5;",7d,6c,44,db) + 3) + HX_("m",6d,00,00,00));
HXDLIN( 351)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("black",bf,d5,f1,b4)) ){
HXLINE( 331)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 0) + HX_("m",6d,00,00,00));
HXDLIN( 331)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("blink",5c,f1,f7,b4)) ){
HXLINE( 327)			return HX_("\x1b""[5m",78,fe,1d,12);
HXDLIN( 327)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("blue",9a,42,19,41)) ){
HXLINE( 335)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 4) + HX_("m",6d,00,00,00));
HXDLIN( 335)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("bold",85,81,1b,41)) ){
HXLINE( 323)			return HX_("\x1b""[1m",fc,fa,1d,12);
HXDLIN( 323)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("cyan",23,45,cc,41)) ){
HXLINE( 337)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 6) + HX_("m",6d,00,00,00));
HXDLIN( 337)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("dim",48,3d,4c,00)) ){
HXLINE( 324)			return HX_("\x1b""[2m",db,fb,1d,12);
HXDLIN( 324)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("green",c3,0e,ed,99)) ){
HXLINE( 333)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 2) + HX_("m",6d,00,00,00));
HXDLIN( 333)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("hidden",6a,ff,95,4c)) ){
HXLINE( 329)			return HX_("\x1b""[8m",15,01,1e,12);
HXDLIN( 329)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("invert",16,e7,d8,9f)) ){
HXLINE( 328)			return HX_("\x1b""[7m",36,00,1e,12);
HXDLIN( 328)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("italic",f0,2e,64,06)) ){
HXLINE( 325)			return HX_("\x1b""[3m",ba,fc,1d,12);
HXDLIN( 325)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_black",56,f2,92,e0)) ){
HXLINE( 339)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 8) + HX_("m",6d,00,00,00));
HXDLIN( 339)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_blue",e3,05,03,e2)) ){
HXLINE( 343)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 12) + HX_("m",6d,00,00,00));
HXDLIN( 343)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_cyan",6c,08,b6,e2)) ){
HXLINE( 345)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 14) + HX_("m",6d,00,00,00));
HXDLIN( 345)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_green",5a,2b,8e,c5)) ){
HXLINE( 341)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 10) + HX_("m",6d,00,00,00));
HXDLIN( 341)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_magenta",80,6a,30,3a)) ){
HXLINE( 344)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 13) + HX_("m",6d,00,00,00));
HXDLIN( 344)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_red",28,d2,66,cd)) ){
HXLINE( 340)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 9) + HX_("m",6d,00,00,00));
HXDLIN( 340)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_white",40,67,5e,f5)) ){
HXLINE( 346)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 15) + HX_("m",6d,00,00,00));
HXDLIN( 346)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("light_yellow",fd,86,b4,d1)) ){
HXLINE( 342)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 11) + HX_("m",6d,00,00,00));
HXDLIN( 342)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("magenta",29,ba,9d,0e)) ){
HXLINE( 336)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 5) + HX_("m",6d,00,00,00));
HXDLIN( 336)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("red",51,d9,56,00)) ){
HXLINE( 332)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 1) + HX_("m",6d,00,00,00));
HXDLIN( 332)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("reset",cf,49,c8,e6)) ){
HXLINE( 321)			return HX_("\x1b""[m",8d,cc,14,00);
HXDLIN( 321)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("underline",0c,15,d1,87)) ){
HXLINE( 326)			return HX_("\x1b""[4m",99,fd,1d,12);
HXDLIN( 326)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("white",a9,4a,bd,c9)) ){
HXLINE( 338)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 7) + HX_("m",6d,00,00,00));
HXDLIN( 338)			goto _hx_goto_9;
            		}
            		if (  (_hx_switch_0==HX_("yellow",74,9f,5c,d0)) ){
HXLINE( 334)			return ((HX_("\x1b""[38;5;",fc,d7,dd,47) + 3) + HX_("m",6d,00,00,00));
HXDLIN( 334)			goto _hx_goto_9;
            		}
            		/* default */{
HXLINE( 365)			return HX_("",00,00,00,00);
            		}
            		_hx_goto_9:;
HXLINE( 320)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Console_obj,getAsciiFormat,return )

 ::Dynamic Console_obj::rgbToAscii256(int r,int g,int b){
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(2)
            		int _hx_run(int c,::Array< int > set){
            			HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_378_rgbToAscii256)
HXLINE( 379)			Float delta = ::Math_obj::POSITIVE_INFINITY;
HXLINE( 380)			int index = -1;
HXLINE( 381)			{
HXLINE( 381)				int _g = 0;
HXDLIN( 381)				int _g1 = set->length;
HXDLIN( 381)				while((_g < _g1)){
HXLINE( 381)					_g = (_g + 1);
HXDLIN( 381)					int i = (_g - 1);
HXLINE( 382)					Float d = ::Math_obj::abs(( (Float)((c - set->__get(i))) ));
HXLINE( 383)					if ((d < delta)) {
HXLINE( 384)						delta = d;
HXLINE( 385)						index = i;
            					}
            				}
            			}
HXLINE( 388)			return index;
            		}
            		HX_END_LOCAL_FUNC2(return)

            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_375_rgbToAscii256)
HXLINE( 378)		 ::Dynamic nearIdx =  ::Dynamic(new _hx_Closure_0());
HXLINE( 398)		::Array< int > colorSteps = ::Array_obj< int >::fromData( _hx_array_data_e6271337_14,6);
HXLINE( 399)		int ir = ( (int)(nearIdx(r,colorSteps)) );
HXDLIN( 399)		int ig = ( (int)(nearIdx(g,colorSteps)) );
HXDLIN( 399)		int ib = ( (int)(nearIdx(b,colorSteps)) );
HXLINE( 400)		Float ier = ::Math_obj::abs(( (Float)((r - colorSteps->__get(ir))) ));
HXDLIN( 400)		Float ieg = ::Math_obj::abs(( (Float)((g - colorSteps->__get(ig))) ));
HXDLIN( 400)		Float ieb = ::Math_obj::abs(( (Float)((b - colorSteps->__get(ib))) ));
HXLINE( 401)		Float averageColorError = ((ier + ieg) + ieb);
HXLINE( 406)		int jr = ::Math_obj::round((( (Float)((r - 8)) ) / ( (Float)(10) )));
HXDLIN( 406)		int jg = ::Math_obj::round((( (Float)((g - 8)) ) / ( (Float)(10) )));
HXDLIN( 406)		int jb = ::Math_obj::round((( (Float)((b - 8)) ) / ( (Float)(10) )));
HXLINE( 407)		Float jer = ::Math_obj::abs((( (Float)(r) ) - ::Math_obj::max(::Math_obj::min(( (Float)(((jr * 10) + 8)) ),( (Float)(238) )),( (Float)(8) ))));
HXLINE( 408)		Float jeg = ::Math_obj::abs((( (Float)(g) ) - ::Math_obj::max(::Math_obj::min(( (Float)(((jg * 10) + 8)) ),( (Float)(238) )),( (Float)(8) ))));
HXLINE( 409)		Float jeb = ::Math_obj::abs((( (Float)(b) ) - ::Math_obj::max(::Math_obj::min(( (Float)(((jb * 10) + 8)) ),( (Float)(238) )),( (Float)(8) ))));
HXLINE( 410)		Float averageGrayError = ((jer + jeg) + jeb);
HXLINE( 413)		bool _hx_tmp;
HXDLIN( 413)		bool _hx_tmp1;
HXDLIN( 413)		if ((averageGrayError < averageColorError)) {
HXLINE( 413)			_hx_tmp1 = (r == g);
            		}
            		else {
HXLINE( 413)			_hx_tmp1 = false;
            		}
HXDLIN( 413)		if (_hx_tmp1) {
HXLINE( 413)			_hx_tmp = (g == b);
            		}
            		else {
HXLINE( 413)			_hx_tmp = false;
            		}
HXDLIN( 413)		if (_hx_tmp) {
HXLINE( 414)			int grayIndex = (jr + 232);
HXLINE( 415)			return grayIndex;
            		}
            		else {
HXLINE( 417)			int colorIndex = (((16 + (ir * 36)) + (ig * 6)) + ib);
HXLINE( 418)			return colorIndex;
            		}
HXLINE( 413)		return 0;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(Console_obj,rgbToAscii256,return )

::String Console_obj::getBrowserFormat(::String flag){
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_422_getBrowserFormat)
HXLINE( 424)		if ((flag.charAt(0) == HX_("#",23,00,00,00))) {
HXLINE( 425)			return (HX_("color: ",c9,02,66,ef) + flag);
            		}
HXLINE( 429)		if ((flag.substr(0,3) == HX_("bg#",be,b6,4a,00))) {
HXLINE( 430)			return (HX_("background-color: ",2a,44,1c,c4) + flag.substr(2,null()));
            		}
HXLINE( 434)		if ((flag.charAt(0) == HX_("{",7b,00,00,00))) {
HXLINE( 436)			return flag.substr(1,(flag.length - 2));
            		}
HXLINE( 439)		::String _hx_switch_0 = flag;
            		if (  (_hx_switch_0==HX_("bg_black",85,94,4b,51)) ){
HXLINE( 468)			return HX_("background-color: black",55,39,dc,9a);
HXDLIN( 468)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_blue",94,fe,23,0e)) ){
HXLINE( 472)			return HX_("background-color: blue",c4,e3,7b,b1);
HXDLIN( 472)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_cyan",1d,01,d7,0e)) ){
HXLINE( 474)			return HX_("background-color: cyan",4d,e6,2e,b2);
HXDLIN( 474)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_green",89,cd,46,36)) ){
HXLINE( 470)			return HX_("background-color: green",59,72,d7,7f);
HXDLIN( 470)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_black",9c,09,69,dd)) ){
HXLINE( 476)			return HX_("background-color: gray",0d,71,ce,b4);
HXDLIN( 476)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_blue",5d,f9,41,dc)) ){
HXLINE( 480)			return HX_("background-color: lightBlue",26,09,aa,e6);
HXDLIN( 480)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_cyan",e6,fb,f4,dc)) ){
HXLINE( 482)			return HX_("background-color: lightCyan",af,0b,5d,e7);
HXDLIN( 482)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_green",a0,42,64,c2)) ){
HXLINE( 478)			return HX_("background-color: lightGreen",b7,02,0a,d3);
HXDLIN( 478)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_magenta",46,5f,2f,aa)) ){
HXLINE( 481)			return HX_("background-color: lightPink",02,b9,e8,ef);
HXDLIN( 481)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_red",ee,6b,ce,2d)) ){
HXLINE( 477)			return HX_("background-color: salmon",18,a5,cb,63);
HXDLIN( 477)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_white",86,7e,34,f2)) ){
HXLINE( 483)			return HX_("background-color: white",3f,ae,a7,af);
HXDLIN( 483)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_light_yellow",f7,cc,32,10)) ){
HXLINE( 479)			return HX_("background-color: lightYellow",00,21,95,90);
HXDLIN( 479)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_magenta",6f,36,f9,c3)) ){
HXLINE( 473)			return HX_("background-color: magenta",3f,af,98,0e);
HXDLIN( 473)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_red",97,3a,61,bc)) ){
HXLINE( 469)			return HX_("background-color: red",67,0b,00,c4);
HXDLIN( 469)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_white",6f,09,17,66)) ){
HXLINE( 475)			return HX_("background-color: whiteSmoke",b0,4c,e0,8e);
HXDLIN( 475)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bg_yellow",ee,cd,89,02)) ){
HXLINE( 471)			return HX_("background-color: gold",ca,33,cc,b4);
HXDLIN( 471)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("black",bf,d5,f1,b4)) ){
HXLINE( 450)			return HX_("color: black",56,1a,40,48);
HXDLIN( 450)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("blink",5c,f1,f7,b4)) ){
HXLINE( 446)			return HX_("text-decoration: blink",e6,ce,a6,07);
HXDLIN( 446)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("blue",9a,42,19,41)) ){
HXLINE( 454)			return HX_("color: blue",e3,dd,32,64);
HXDLIN( 454)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("bold",85,81,1b,41)) ){
HXLINE( 442)			return HX_("font-weight: bold",21,d7,c7,20);
HXDLIN( 442)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("cyan",23,45,cc,41)) ){
HXLINE( 456)			return HX_("color: cyan",6c,e0,e5,64);
HXDLIN( 456)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("dim",48,3d,4c,00)) ){
HXLINE( 444)			return HX_("color: gray",2c,6b,85,67);
HXDLIN( 444)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("green",c3,0e,ed,99)) ){
HXLINE( 452)			return HX_("color: green",5a,53,3b,2d);
HXDLIN( 452)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("hidden",6a,ff,95,4c)) ){
HXLINE( 448)			return HX_("visibility: hidden; color: white",27,a0,fd,fd);
HXDLIN( 448)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("invert",16,e7,d8,9f)) ){
HXLINE( 447)			return HX_("-webkit-filter: invert(100%); filter: invert(100%)",65,80,5b,b3);
HXDLIN( 447)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("italic",f0,2e,64,06)) ){
HXLINE( 443)			return HX_("font-style: italic",09,92,37,fd);
HXDLIN( 443)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_black",56,f2,92,e0)) ){
HXLINE( 459)			return HX_("color: gray",2c,6b,85,67);
HXDLIN( 459)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_blue",e3,05,03,e2)) ){
HXLINE( 463)			return HX_("color: lightBlue",a7,fe,78,3d);
HXDLIN( 463)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_cyan",6c,08,b6,e2)) ){
HXLINE( 465)			return HX_("color: lightCyan",30,01,2c,3e);
HXDLIN( 465)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_green",5a,2b,8e,c5)) ){
HXLINE( 461)			return HX_("color: lightGreen",16,de,51,71);
HXDLIN( 461)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_magenta",80,6a,30,3a)) ){
HXLINE( 464)			return HX_("color: lightPink",83,ae,b7,46);
HXDLIN( 464)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_red",28,d2,66,cd)) ){
HXLINE( 460)			return HX_("color: salmon",f7,a4,cc,6d);
HXDLIN( 460)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_white",40,67,5e,f5)) ){
HXLINE( 466)			return HX_("color: white",40,8f,0b,5d);
HXDLIN( 466)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("light_yellow",fd,86,b4,d1)) ){
HXLINE( 462)			return HX_("color: #ffed88",19,ad,9d,2c);
HXDLIN( 462)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("magenta",29,ba,9d,0e)) ){
HXLINE( 455)			return HX_("color: magenta",80,92,77,c5);
HXDLIN( 455)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("red",51,d9,56,00)) ){
HXLINE( 451)			return HX_("color: red",28,fa,f9,0b);
HXDLIN( 451)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("reset",cf,49,c8,e6)) ){
HXLINE( 440)			return HX_("",00,00,00,00);
HXDLIN( 440)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("underline",0c,15,d1,87)) ){
HXLINE( 445)			return HX_("text-decoration: underline",96,7f,fe,cc);
HXDLIN( 445)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("white",a9,4a,bd,c9)) ){
HXLINE( 457)			return HX_("color: whiteSmoke",0f,28,28,2d);
HXDLIN( 457)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("yellow",74,9f,5c,d0)) ){
HXLINE( 453)			return HX_("color: #f5ba00",c8,4e,fd,f3);
HXDLIN( 453)			goto _hx_goto_15;
            		}
            		/* default */{
HXLINE( 485)			return HX_("",00,00,00,00);
            		}
            		_hx_goto_15:;
HXLINE( 439)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Console_obj,getBrowserFormat,return )

int Console_obj::determineConsoleFormatMode(){
            	HX_GC_STACKFRAME(&_hx_pos_9b0ca03e92855c49_489_determineConsoleFormatMode)
HXLINE( 511)		 ::Dynamic tputColors = ::Console_obj::exec(HX_("tput colors",55,5c,c3,d1),null());
HXLINE( 512)		bool _hx_tmp;
HXDLIN( 512)		if (::hx::IsEq( tputColors->__Field(HX_("exit",1e,f7,1d,43),::hx::paccDynamic),0 )) {
HXLINE( 512)			_hx_tmp = ::hx::IsGreater( ::Std_obj::parseInt(( (::String)(tputColors->__Field(HX_("stdout",cb,bf,f3,07),::hx::paccDynamic)) )),2 );
            		}
            		else {
HXLINE( 512)			_hx_tmp = false;
            		}
HXDLIN( 512)		if (_hx_tmp) {
HXLINE( 513)			return 0;
            		}
HXLINE( 518)		bool winconVTEnabled = false;
HXLINE( 520)		
			#if defined(HX_WINDOWS) && defined(ENABLE_VIRTUAL_TERMINAL_PROCESSING)
			// Set output mode to handle virtual terminal sequences
			HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
			DWORD dwMode = 0;
			if (hOut != INVALID_HANDLE_VALUE && GetConsoleMode(hOut, &dwMode))
			{
				dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
				winconVTEnabled = SetConsoleMode(hOut, dwMode);
			}
			#endif
		;
HXLINE( 533)		if (winconVTEnabled) {
HXLINE( 534)			return 0;
            		}
HXLINE( 549)		::String termEnv = ::Sys_obj::environment()->get_string(HX_("TERM",6c,8f,ba,37));
HXLINE( 551)		bool _hx_tmp1;
HXDLIN( 551)		if (::hx::IsNotNull( termEnv )) {
HXLINE( 551)			_hx_tmp1 =  ::EReg_obj::__alloc( HX_CTX ,HX_("cygwin|xterm|vt100",2a,5a,76,d4),HX_("",00,00,00,00))->match(termEnv);
            		}
            		else {
HXLINE( 551)			_hx_tmp1 = false;
            		}
HXDLIN( 551)		if (_hx_tmp1) {
HXLINE( 552)			return 0;
            		}
HXLINE( 558)		return 2;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Console_obj,determineConsoleFormatMode,return )

 ::Dynamic Console_obj::joinArgs(::Array< ::Dynamic> rest){
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_561_joinArgs)
HXLINE( 562)		 ::Dynamic msg =  ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("pos",94,5d,55,00), ::Dynamic(::hx::Anon_obj::Create(3)
            				->setFixed(0,HX_("max",a4,0a,53,00),19029)
            				->setFixed(1,HX_("min",92,11,53,00),19027)
            				->setFixed(2,HX_("file",7c,ce,bb,43),HX_("/home/bran/haxelib/console,hx/0,2,12/Console.hx",16,c6,e2,be))))
            			->setFixed(1,HX_("expr",35,fd,1d,43),::haxe::macro::ExprDef_obj::EConst(::haxe::macro::Constant_obj::CString(HX_("",00,00,00,00),::haxe::macro::StringLiteralKind_obj::SingleQuotes_dyn()))));
HXLINE( 563)		{
HXLINE( 563)			int _g = 0;
HXDLIN( 563)			int _g1 = rest->length;
HXDLIN( 563)			while((_g < _g1)){
HXLINE( 563)				_g = (_g + 1);
HXDLIN( 563)				int i = (_g - 1);
HXLINE( 564)				 ::Dynamic e = rest->__get(i);
HXLINE( 565)				msg =  ::Dynamic(::hx::Anon_obj::Create(2)
            					->setFixed(0,HX_("pos",94,5d,55,00), ::Dynamic(::hx::Anon_obj::Create(3)
            						->setFixed(0,HX_("max",a4,0a,53,00),19104)
            						->setFixed(1,HX_("min",92,11,53,00),19095)
            						->setFixed(2,HX_("file",7c,ce,bb,43),HX_("/home/bran/haxelib/console,hx/0,2,12/Console.hx",16,c6,e2,be))))
            					->setFixed(1,HX_("expr",35,fd,1d,43),::haxe::macro::ExprDef_obj::EBinop(::haxe::macro::Binop_obj::OpAdd_dyn(),msg,e)));
HXLINE( 566)				if ((i != (rest->length - 1))) {
HXLINE( 567)					msg =  ::Dynamic(::hx::Anon_obj::Create(2)
            						->setFixed(0,HX_("pos",94,5d,55,00), ::Dynamic(::hx::Anon_obj::Create(3)
            							->setFixed(0,HX_("max",a4,0a,53,00),19174)
            							->setFixed(1,HX_("min",92,11,53,00),19152)
            							->setFixed(2,HX_("file",7c,ce,bb,43),HX_("/home/bran/haxelib/console,hx/0,2,12/Console.hx",16,c6,e2,be))))
            						->setFixed(1,HX_("expr",35,fd,1d,43),::haxe::macro::ExprDef_obj::EBinop(::haxe::macro::Binop_obj::OpAdd_dyn(),msg, ::Dynamic(::hx::Anon_obj::Create(2)
            							->setFixed(0,HX_("pos",94,5d,55,00), ::Dynamic(::hx::Anon_obj::Create(3)
            								->setFixed(0,HX_("max",a4,0a,53,00),19174)
            								->setFixed(1,HX_("min",92,11,53,00),19159)
            								->setFixed(2,HX_("file",7c,ce,bb,43),HX_("/home/bran/haxelib/console,hx/0,2,12/Console.hx",16,c6,e2,be))))
            							->setFixed(1,HX_("expr",35,fd,1d,43),::haxe::macro::ExprDef_obj::EConst(::haxe::macro::Constant_obj::CString(HX_("$argSeparator",53,6d,ee,4c),::haxe::macro::StringLiteralKind_obj::SingleQuotes_dyn())))))));
            				}
            			}
            		}
HXLINE( 570)		return msg;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Console_obj,joinArgs,return )

 ::Dynamic Console_obj::exec(::String cmd,::Array< ::String > args){
            	HX_GC_STACKFRAME(&_hx_pos_9b0ca03e92855c49_585_exec)
HXDLIN( 585)		try {
            			HX_STACK_CATCHABLE( ::Dynamic, 0);
HXLINE( 586)			 ::sys::io::Process p =  ::sys::io::Process_obj::__alloc( HX_CTX ,cmd,args,null());
HXLINE( 587)			 ::Dynamic exit = p->exitCode(null());
HXLINE( 588)			::String _hx_stdout = p->_hx_stdout->readAll(null())->toString();
HXLINE( 589)			p->close();
HXLINE( 590)			return  ::Dynamic(::hx::Anon_obj::Create(2)
            				->setFixed(0,HX_("stdout",cb,bf,f3,07),_hx_stdout)
            				->setFixed(1,HX_("exit",1e,f7,1d,43),exit));
            		} catch( ::Dynamic _hx_e) {
            			if (_hx_e.IsClass<  ::Dynamic >() ){
            				HX_STACK_BEGIN_CATCH
            				 ::Dynamic _g = _hx_e;
HXLINE(   1)				{
HXLINE(   1)					null();
            				}
HXLINE( 595)				return  ::Dynamic(::hx::Anon_obj::Create(2)
            					->setFixed(0,HX_("stdout",cb,bf,f3,07),HX_("",00,00,00,00))
            					->setFixed(1,HX_("exit",1e,f7,1d,43),1));
            			}
            			else {
            				HX_STACK_DO_THROW(_hx_e);
            			}
            		}
HXLINE( 585)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Console_obj,exec,return )


Console_obj::Console_obj()
{
}

bool Console_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"exec") ) { outValue = exec_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"print") ) { outValue = print_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"println") ) { outValue = println_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"joinArgs") ) { outValue = joinArgs_dyn(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"logPrefix") ) { outValue = ( logPrefix ); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"formatMode") ) { outValue = ( formatMode ); return true; }
		if (HX_FIELD_EQ(inName,"warnPrefix") ) { outValue = ( warnPrefix ); return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"errorPrefix") ) { outValue = ( errorPrefix ); return true; }
		if (HX_FIELD_EQ(inName,"debugPrefix") ) { outValue = ( debugPrefix ); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"argSeparator") ) { outValue = ( argSeparator ); return true; }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"successPrefix") ) { outValue = ( successPrefix ); return true; }
		if (HX_FIELD_EQ(inName,"rgbToAscii256") ) { outValue = rgbToAscii256_dyn(); return true; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"printIntercept") ) { outValue = ( printIntercept ); return true; }
		if (HX_FIELD_EQ(inName,"printFormatted") ) { outValue = printFormatted_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"getAsciiFormat") ) { outValue = getAsciiFormat_dyn(); return true; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"printlnFormatted") ) { outValue = printlnFormatted_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"formatTagPattern") ) { outValue = ( formatTagPattern ); return true; }
		if (HX_FIELD_EQ(inName,"getBrowserFormat") ) { outValue = getBrowserFormat_dyn(); return true; }
		break;
	case 24:
		if (HX_FIELD_EQ(inName,"unicodeCompatibilityMode") ) { outValue = ( unicodeCompatibilityMode ); return true; }
		break;
	case 26:
		if (HX_FIELD_EQ(inName,"determineConsoleFormatMode") ) { outValue = determineConsoleFormatMode_dyn(); return true; }
		break;
	case 27:
		if (HX_FIELD_EQ(inName,"unicodeCompatibilityEnabled") ) { outValue = ( unicodeCompatibilityEnabled ); return true; }
	}
	return false;
}

bool Console_obj::__SetStatic(const ::String &inName,Dynamic &ioValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 9:
		if (HX_FIELD_EQ(inName,"logPrefix") ) { logPrefix=ioValue.Cast< ::String >(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"formatMode") ) { formatMode=ioValue.Cast< int >(); return true; }
		if (HX_FIELD_EQ(inName,"warnPrefix") ) { warnPrefix=ioValue.Cast< ::String >(); return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"errorPrefix") ) { errorPrefix=ioValue.Cast< ::String >(); return true; }
		if (HX_FIELD_EQ(inName,"debugPrefix") ) { debugPrefix=ioValue.Cast< ::String >(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"argSeparator") ) { argSeparator=ioValue.Cast< ::String >(); return true; }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"successPrefix") ) { successPrefix=ioValue.Cast< ::String >(); return true; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"printIntercept") ) { printIntercept=ioValue.Cast<  ::Dynamic >(); return true; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"formatTagPattern") ) { formatTagPattern=ioValue.Cast<  ::EReg >(); return true; }
		break;
	case 24:
		if (HX_FIELD_EQ(inName,"unicodeCompatibilityMode") ) { unicodeCompatibilityMode=ioValue.Cast< int >(); return true; }
		break;
	case 27:
		if (HX_FIELD_EQ(inName,"unicodeCompatibilityEnabled") ) { unicodeCompatibilityEnabled=ioValue.Cast< bool >(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Console_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo Console_obj_sStaticStorageInfo[] = {
	{::hx::fsInt,(void *) &Console_obj::formatMode,HX_("formatMode",3a,f6,c5,07)},
	{::hx::fsString,(void *) &Console_obj::logPrefix,HX_("logPrefix",36,dd,25,69)},
	{::hx::fsString,(void *) &Console_obj::warnPrefix,HX_("warnPrefix",78,a8,11,8a)},
	{::hx::fsString,(void *) &Console_obj::errorPrefix,HX_("errorPrefix",7a,1f,24,9d)},
	{::hx::fsString,(void *) &Console_obj::successPrefix,HX_("successPrefix",b5,a7,1c,11)},
	{::hx::fsString,(void *) &Console_obj::debugPrefix,HX_("debugPrefix",45,a0,29,b7)},
	{::hx::fsObject /*  ::Dynamic */ ,(void *) &Console_obj::printIntercept,HX_("printIntercept",55,3c,15,8e)},
	{::hx::fsString,(void *) &Console_obj::argSeparator,HX_("argSeparator",2f,c7,dc,7d)},
	{::hx::fsInt,(void *) &Console_obj::unicodeCompatibilityMode,HX_("unicodeCompatibilityMode",d6,b9,fe,8a)},
	{::hx::fsBool,(void *) &Console_obj::unicodeCompatibilityEnabled,HX_("unicodeCompatibilityEnabled",ee,67,ca,4e)},
	{::hx::fsObject /*  ::EReg */ ,(void *) &Console_obj::formatTagPattern,HX_("formatTagPattern",2d,91,bc,90)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void Console_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(Console_obj::formatMode,"formatMode");
	HX_MARK_MEMBER_NAME(Console_obj::logPrefix,"logPrefix");
	HX_MARK_MEMBER_NAME(Console_obj::warnPrefix,"warnPrefix");
	HX_MARK_MEMBER_NAME(Console_obj::errorPrefix,"errorPrefix");
	HX_MARK_MEMBER_NAME(Console_obj::successPrefix,"successPrefix");
	HX_MARK_MEMBER_NAME(Console_obj::debugPrefix,"debugPrefix");
	HX_MARK_MEMBER_NAME(Console_obj::printIntercept,"printIntercept");
	HX_MARK_MEMBER_NAME(Console_obj::argSeparator,"argSeparator");
	HX_MARK_MEMBER_NAME(Console_obj::unicodeCompatibilityMode,"unicodeCompatibilityMode");
	HX_MARK_MEMBER_NAME(Console_obj::unicodeCompatibilityEnabled,"unicodeCompatibilityEnabled");
	HX_MARK_MEMBER_NAME(Console_obj::formatTagPattern,"formatTagPattern");
};

#ifdef HXCPP_VISIT_ALLOCS
static void Console_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(Console_obj::formatMode,"formatMode");
	HX_VISIT_MEMBER_NAME(Console_obj::logPrefix,"logPrefix");
	HX_VISIT_MEMBER_NAME(Console_obj::warnPrefix,"warnPrefix");
	HX_VISIT_MEMBER_NAME(Console_obj::errorPrefix,"errorPrefix");
	HX_VISIT_MEMBER_NAME(Console_obj::successPrefix,"successPrefix");
	HX_VISIT_MEMBER_NAME(Console_obj::debugPrefix,"debugPrefix");
	HX_VISIT_MEMBER_NAME(Console_obj::printIntercept,"printIntercept");
	HX_VISIT_MEMBER_NAME(Console_obj::argSeparator,"argSeparator");
	HX_VISIT_MEMBER_NAME(Console_obj::unicodeCompatibilityMode,"unicodeCompatibilityMode");
	HX_VISIT_MEMBER_NAME(Console_obj::unicodeCompatibilityEnabled,"unicodeCompatibilityEnabled");
	HX_VISIT_MEMBER_NAME(Console_obj::formatTagPattern,"formatTagPattern");
};

#endif

::hx::Class Console_obj::__mClass;

static ::String Console_obj_sStaticFields[] = {
	HX_("formatMode",3a,f6,c5,07),
	HX_("logPrefix",36,dd,25,69),
	HX_("warnPrefix",78,a8,11,8a),
	HX_("errorPrefix",7a,1f,24,9d),
	HX_("successPrefix",b5,a7,1c,11),
	HX_("debugPrefix",45,a0,29,b7),
	HX_("printIntercept",55,3c,15,8e),
	HX_("argSeparator",2f,c7,dc,7d),
	HX_("unicodeCompatibilityMode",d6,b9,fe,8a),
	HX_("unicodeCompatibilityEnabled",ee,67,ca,4e),
	HX_("printlnFormatted",0d,79,b9,d2),
	HX_("println",ef,db,33,84),
	HX_("formatTagPattern",2d,91,bc,90),
	HX_("printFormatted",0f,85,9b,6f),
	HX_("print",2d,58,8b,c8),
	HX_("getAsciiFormat",72,f2,d5,06),
	HX_("rgbToAscii256",6a,64,e6,eb),
	HX_("getBrowserFormat",89,d6,28,b2),
	HX_("determineConsoleFormatMode",5e,e7,98,8b),
	HX_("joinArgs",67,2a,8c,33),
	HX_("exec",91,f3,1d,43),
	::String(null())
};

void Console_obj::__register()
{
	Console_obj _hx_dummy;
	Console_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Console",37,13,27,e6);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Console_obj::__GetStatic;
	__mClass->mSetStaticField = &Console_obj::__SetStatic;
	__mClass->mMarkFunc = Console_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Console_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Console_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Console_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Console_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Console_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Console_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_13_boot)
HXDLIN(  13)		formatMode = ::Console_obj::determineConsoleFormatMode();
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_15_boot)
HXDLIN(  15)		logPrefix = HX_("<b,gray>><//> ",b5,86,c0,99);
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_16_boot)
HXDLIN(  16)		warnPrefix = HX_("<b,yellow>><//> ",c4,ed,da,27);
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_17_boot)
HXDLIN(  17)		errorPrefix = HX_("<b,red>></b> ",46,bd,75,64);
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_18_boot)
HXDLIN(  18)		successPrefix = HX_("<b,light_green>><//> ",6a,b1,9e,f9);
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_19_boot)
HXDLIN(  19)		debugPrefix = HX_("<b,magenta>><//> ",7b,0f,69,93);
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_24_boot)
HXDLIN(  24)		printIntercept = null();
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_26_boot)
HXDLIN(  26)		argSeparator = HX_(" ",20,00,00,00);
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_27_boot)
HXDLIN(  27)			if ((::Sys_obj::systemName() == HX_("Windows",63,06,c6,b5))) {
HXDLIN(  27)				return 1;
            			}
            			else {
HXDLIN(  27)				return 0;
            			}
HXDLIN(  27)			return null();
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_27_boot)
HXDLIN(  27)		unicodeCompatibilityMode = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            	HX_STACKFRAME(&_hx_pos_9b0ca03e92855c49_28_boot)
HXDLIN(  28)		unicodeCompatibilityEnabled = false;
            	}
{
            	HX_GC_STACKFRAME(&_hx_pos_9b0ca03e92855c49_109_boot)
HXDLIN( 109)		formatTagPattern =  ::EReg_obj::__alloc( HX_CTX ,HX_("<(/)?([^><{}\\s]*|{[^}<>]*})>",3e,c4,f7,11),HX_("g",67,00,00,00));
            	}
}

