// Generated by Haxe 4.2.1
#include <hxcpp.h>

#ifndef INCLUDED_markdown_ElementNode
#include <markdown/ElementNode.h>
#endif
#ifndef INCLUDED_markdown_Node
#include <markdown/Node.h>
#endif
#ifndef INCLUDED_markdown_NodeVisitor
#include <markdown/NodeVisitor.h>
#endif
#ifndef INCLUDED_markdown_TextNode
#include <markdown/TextNode.h>
#endif

namespace markdown{


static ::String NodeVisitor_obj_sMemberFields[] = {
	HX_("visitText",18,b4,e2,5c),
	HX_("visitElementBefore",90,7f,f7,b0),
	HX_("visitElementAfter",2b,08,6b,b6),
	::String(null()) };

::hx::Class NodeVisitor_obj::__mClass;

void NodeVisitor_obj::__register()
{
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("markdown.NodeVisitor",ad,9d,95,2a);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(NodeVisitor_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TIsInterface< (int)0x0d07169d >;
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace markdown
