// Generated by Haxe 4.2.1
#include <hxcpp.h>

#ifndef INCLUDED_EReg
#include <EReg.h>
#endif
#ifndef INCLUDED__Console_FormatFlag_Impl_
#include <_Console/FormatFlag_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_676_fromString,"_Console.FormatFlag_Impl_","fromString",0x356ee830,"_Console.FormatFlag_Impl_.fromString","Console.hx",676,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_634_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",634,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_635_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",635,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_636_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",636,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_637_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",637,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_638_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",638,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_639_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",639,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_640_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",640,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_641_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",641,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_642_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",642,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_643_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",643,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_644_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",644,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_645_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",645,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_646_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",646,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_647_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",647,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_648_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",648,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_649_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",649,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_650_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",650,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_651_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",651,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_652_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",652,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_653_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",653,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_654_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",654,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_655_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",655,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_656_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",656,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_657_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",657,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_658_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",658,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_659_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",659,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_660_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",660,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_661_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",661,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_662_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",662,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_663_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",663,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_664_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",664,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_665_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",665,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_666_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",666,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_667_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",667,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_668_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",668,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_669_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",669,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_670_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",670,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_671_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",671,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_672_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",672,0xdfc4cbe7)
HX_LOCAL_STACK_FRAME(_hx_pos_58a68fd115af502b_673_boot,"_Console.FormatFlag_Impl_","boot",0x887b20c7,"_Console.FormatFlag_Impl_.boot","Console.hx",673,0xdfc4cbe7)
namespace _Console{

void FormatFlag_Impl__obj::__construct() { }

Dynamic FormatFlag_Impl__obj::__CreateEmpty() { return new FormatFlag_Impl__obj; }

void *FormatFlag_Impl__obj::_hx_vtable = 0;

Dynamic FormatFlag_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< FormatFlag_Impl__obj > _hx_result = new FormatFlag_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool FormatFlag_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x2eb0dbbb;
}

::String FormatFlag_Impl__obj::RESET;

::String FormatFlag_Impl__obj::BOLD;

::String FormatFlag_Impl__obj::ITALIC;

::String FormatFlag_Impl__obj::DIM;

::String FormatFlag_Impl__obj::UNDERLINE;

::String FormatFlag_Impl__obj::BLINK;

::String FormatFlag_Impl__obj::INVERT;

::String FormatFlag_Impl__obj::HIDDEN;

::String FormatFlag_Impl__obj::BLACK;

::String FormatFlag_Impl__obj::RED;

::String FormatFlag_Impl__obj::GREEN;

::String FormatFlag_Impl__obj::YELLOW;

::String FormatFlag_Impl__obj::BLUE;

::String FormatFlag_Impl__obj::MAGENTA;

::String FormatFlag_Impl__obj::CYAN;

::String FormatFlag_Impl__obj::WHITE;

::String FormatFlag_Impl__obj::LIGHT_BLACK;

::String FormatFlag_Impl__obj::LIGHT_RED;

::String FormatFlag_Impl__obj::LIGHT_GREEN;

::String FormatFlag_Impl__obj::LIGHT_YELLOW;

::String FormatFlag_Impl__obj::LIGHT_BLUE;

::String FormatFlag_Impl__obj::LIGHT_MAGENTA;

::String FormatFlag_Impl__obj::LIGHT_CYAN;

::String FormatFlag_Impl__obj::LIGHT_WHITE;

::String FormatFlag_Impl__obj::BG_BLACK;

::String FormatFlag_Impl__obj::BG_RED;

::String FormatFlag_Impl__obj::BG_GREEN;

::String FormatFlag_Impl__obj::BG_YELLOW;

::String FormatFlag_Impl__obj::BG_BLUE;

::String FormatFlag_Impl__obj::BG_MAGENTA;

::String FormatFlag_Impl__obj::BG_CYAN;

::String FormatFlag_Impl__obj::BG_WHITE;

::String FormatFlag_Impl__obj::BG_LIGHT_BLACK;

::String FormatFlag_Impl__obj::BG_LIGHT_RED;

::String FormatFlag_Impl__obj::BG_LIGHT_GREEN;

::String FormatFlag_Impl__obj::BG_LIGHT_YELLOW;

::String FormatFlag_Impl__obj::BG_LIGHT_BLUE;

::String FormatFlag_Impl__obj::BG_LIGHT_MAGENTA;

::String FormatFlag_Impl__obj::BG_LIGHT_CYAN;

::String FormatFlag_Impl__obj::BG_LIGHT_WHITE;

::String FormatFlag_Impl__obj::fromString(::String str){
            	HX_GC_STACKFRAME(&_hx_pos_58a68fd115af502b_676_fromString)
HXLINE( 677)		str = str.toLowerCase();
HXLINE( 680)		bool _hx_tmp;
HXDLIN( 680)		if ((str.charAt(0) != HX_("#",23,00,00,00))) {
HXLINE( 680)			_hx_tmp = (str.substr(0,3) == HX_("bg#",be,b6,4a,00));
            		}
            		else {
HXLINE( 680)			_hx_tmp = true;
            		}
HXDLIN( 680)		if (_hx_tmp) {
HXLINE( 681)			int hIdx = str.indexOf(HX_("#",23,00,00,00),null());
HXLINE( 682)			::String hex = str.substr((hIdx + 1),null());
HXLINE( 685)			if ((hex.length == 3)) {
HXLINE( 686)				::Array< ::String > a = hex.split(HX_("",00,00,00,00));
HXLINE( 687)				hex = ::Array_obj< ::String >::__new(6)->init(0,a->__get(0))->init(1,a->__get(0))->init(2,a->__get(1))->init(3,a->__get(1))->init(4,a->__get(2))->init(5,a->__get(2))->join(HX_("",00,00,00,00));
            			}
HXLINE( 691)			bool _hx_tmp;
HXDLIN( 691)			if (!( ::EReg_obj::__alloc( HX_CTX ,HX_("[^0-9a-f]",3c,fd,82,d8),HX_("i",69,00,00,00))->match(hex))) {
HXLINE( 691)				_hx_tmp = (hex.length < 6);
            			}
            			else {
HXLINE( 691)				_hx_tmp = true;
            			}
HXDLIN( 691)			if (_hx_tmp) {
HXLINE( 693)				return HX_("",00,00,00,00);
            			}
HXLINE( 696)			::String normalized = ((str.substring(0,hIdx) + HX_("#",23,00,00,00)) + hex);
HXLINE( 698)			return normalized;
            		}
HXLINE( 702)		::String _hx_switch_0 = str;
            		if (  (_hx_switch_0==HX_("!",21,00,00,00)) ){
HXLINE( 704)			return HX_("invert",16,e7,d8,9f);
HXDLIN( 704)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("/",2f,00,00,00)) ){
HXLINE( 703)			return HX_("reset",cf,49,c8,e6);
HXDLIN( 703)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("b",62,00,00,00)) ){
HXLINE( 706)			return HX_("bold",85,81,1b,41);
HXDLIN( 706)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("bg_gray",dd,8b,76,11)) ){
HXLINE( 709)			return HX_("bg_light_black",9c,09,69,dd);
HXDLIN( 709)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("gray",e3,cf,6b,44)) ){
HXLINE( 708)			return HX_("light_black",56,f2,92,e0);
HXDLIN( 708)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("i",69,00,00,00)) ){
HXLINE( 707)			return HX_("italic",f0,2e,64,06);
HXDLIN( 707)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("u",75,00,00,00)) ){
HXLINE( 705)			return HX_("underline",0c,15,d1,87);
HXDLIN( 705)			goto _hx_goto_0;
            		}
            		/* default */{
HXLINE( 710)			return str;
            		}
            		_hx_goto_0:;
HXLINE( 702)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FormatFlag_Impl__obj,fromString,return )


FormatFlag_Impl__obj::FormatFlag_Impl__obj()
{
}

bool FormatFlag_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 10:
		if (HX_FIELD_EQ(inName,"fromString") ) { outValue = fromString_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *FormatFlag_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo FormatFlag_Impl__obj_sStaticStorageInfo[] = {
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::RESET,HX_("RESET",af,81,b6,64)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BOLD,HX_("BOLD",85,49,dc,2b)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::ITALIC,HX_("ITALIC",f0,da,e6,b8)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::DIM,HX_("DIM",28,d9,33,00)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::UNDERLINE,HX_("UNDERLINE",ec,84,29,83)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BLINK,HX_("BLINK",3c,29,e6,32)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::INVERT,HX_("INVERT",16,93,5b,52)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::HIDDEN,HX_("HIDDEN",6a,ab,18,ff)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BLACK,HX_("BLACK",9f,0d,e0,32)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::RED,HX_("RED",31,75,3e,00)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::GREEN,HX_("GREEN",a3,46,db,17)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::YELLOW,HX_("YELLOW",74,4b,df,82)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BLUE,HX_("BLUE",9a,0a,da,2b)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::MAGENTA,HX_("MAGENTA",09,8e,71,8e)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::CYAN,HX_("CYAN",23,0d,8d,2c)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::WHITE,HX_("WHITE",89,82,ab,47)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_BLACK,HX_("LIGHT_BLACK",16,8a,3a,82)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_RED,HX_("LIGHT_RED",e8,15,e6,dd)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_GREEN,HX_("LIGHT_GREEN",1a,c3,35,67)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_YELLOW,HX_("LIGHT_YELLOW",1d,b7,b1,a2)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_BLUE,HX_("LIGHT_BLUE",03,0a,df,40)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_MAGENTA,HX_("LIGHT_MAGENTA",40,56,bd,46)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_CYAN,HX_("LIGHT_CYAN",8c,0c,92,41)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::LIGHT_WHITE,HX_("LIGHT_WHITE",00,ff,05,97)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_BLACK,HX_("BG_BLACK",65,b0,3c,76)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_RED,HX_("BG_RED",77,ba,0a,84)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_GREEN,HX_("BG_GREEN",69,e9,37,5b)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_YELLOW,HX_("BG_YELLOW",ee,15,91,30)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_BLUE,HX_("BG_BLUE",94,62,ca,fa)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_MAGENTA,HX_("BG_MAGENTA",4f,ee,50,dc)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_CYAN,HX_("BG_CYAN",1d,65,7d,fb)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_WHITE,HX_("BG_WHITE",4f,25,08,8b)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_BLACK,HX_("BG_LIGHT_BLACK",5c,85,56,71)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_RED,HX_("BG_LIGHT_RED",ae,93,92,ea)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_GREEN,HX_("BG_LIGHT_GREEN",60,be,51,56)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_YELLOW,HX_("BG_LIGHT_YELLOW",17,99,11,ec)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_BLUE,HX_("BG_LIGHT_BLUE",7d,99,20,4b)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_MAGENTA,HX_("BG_LIGHT_MAGENTA",06,2f,43,31)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_CYAN,HX_("BG_LIGHT_CYAN",06,9c,d3,4b)},
	{::hx::fsString,(void *) &FormatFlag_Impl__obj::BG_LIGHT_WHITE,HX_("BG_LIGHT_WHITE",46,fa,21,86)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void FormatFlag_Impl__obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::RESET,"RESET");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BOLD,"BOLD");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::ITALIC,"ITALIC");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::DIM,"DIM");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::UNDERLINE,"UNDERLINE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BLINK,"BLINK");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::INVERT,"INVERT");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::HIDDEN,"HIDDEN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BLACK,"BLACK");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::RED,"RED");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::GREEN,"GREEN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::YELLOW,"YELLOW");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BLUE,"BLUE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::MAGENTA,"MAGENTA");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::CYAN,"CYAN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::WHITE,"WHITE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_BLACK,"LIGHT_BLACK");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_RED,"LIGHT_RED");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_GREEN,"LIGHT_GREEN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_YELLOW,"LIGHT_YELLOW");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_BLUE,"LIGHT_BLUE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_MAGENTA,"LIGHT_MAGENTA");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_CYAN,"LIGHT_CYAN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_WHITE,"LIGHT_WHITE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_BLACK,"BG_BLACK");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_RED,"BG_RED");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_GREEN,"BG_GREEN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_YELLOW,"BG_YELLOW");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_BLUE,"BG_BLUE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_MAGENTA,"BG_MAGENTA");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_CYAN,"BG_CYAN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_WHITE,"BG_WHITE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_BLACK,"BG_LIGHT_BLACK");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_RED,"BG_LIGHT_RED");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_GREEN,"BG_LIGHT_GREEN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_YELLOW,"BG_LIGHT_YELLOW");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_BLUE,"BG_LIGHT_BLUE");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_MAGENTA,"BG_LIGHT_MAGENTA");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_CYAN,"BG_LIGHT_CYAN");
	HX_MARK_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_WHITE,"BG_LIGHT_WHITE");
};

#ifdef HXCPP_VISIT_ALLOCS
static void FormatFlag_Impl__obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::RESET,"RESET");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BOLD,"BOLD");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::ITALIC,"ITALIC");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::DIM,"DIM");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::UNDERLINE,"UNDERLINE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BLINK,"BLINK");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::INVERT,"INVERT");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::HIDDEN,"HIDDEN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BLACK,"BLACK");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::RED,"RED");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::GREEN,"GREEN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::YELLOW,"YELLOW");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BLUE,"BLUE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::MAGENTA,"MAGENTA");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::CYAN,"CYAN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::WHITE,"WHITE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_BLACK,"LIGHT_BLACK");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_RED,"LIGHT_RED");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_GREEN,"LIGHT_GREEN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_YELLOW,"LIGHT_YELLOW");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_BLUE,"LIGHT_BLUE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_MAGENTA,"LIGHT_MAGENTA");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_CYAN,"LIGHT_CYAN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::LIGHT_WHITE,"LIGHT_WHITE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_BLACK,"BG_BLACK");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_RED,"BG_RED");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_GREEN,"BG_GREEN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_YELLOW,"BG_YELLOW");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_BLUE,"BG_BLUE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_MAGENTA,"BG_MAGENTA");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_CYAN,"BG_CYAN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_WHITE,"BG_WHITE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_BLACK,"BG_LIGHT_BLACK");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_RED,"BG_LIGHT_RED");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_GREEN,"BG_LIGHT_GREEN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_YELLOW,"BG_LIGHT_YELLOW");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_BLUE,"BG_LIGHT_BLUE");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_MAGENTA,"BG_LIGHT_MAGENTA");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_CYAN,"BG_LIGHT_CYAN");
	HX_VISIT_MEMBER_NAME(FormatFlag_Impl__obj::BG_LIGHT_WHITE,"BG_LIGHT_WHITE");
};

#endif

::hx::Class FormatFlag_Impl__obj::__mClass;

static ::String FormatFlag_Impl__obj_sStaticFields[] = {
	HX_("RESET",af,81,b6,64),
	HX_("BOLD",85,49,dc,2b),
	HX_("ITALIC",f0,da,e6,b8),
	HX_("DIM",28,d9,33,00),
	HX_("UNDERLINE",ec,84,29,83),
	HX_("BLINK",3c,29,e6,32),
	HX_("INVERT",16,93,5b,52),
	HX_("HIDDEN",6a,ab,18,ff),
	HX_("BLACK",9f,0d,e0,32),
	HX_("RED",31,75,3e,00),
	HX_("GREEN",a3,46,db,17),
	HX_("YELLOW",74,4b,df,82),
	HX_("BLUE",9a,0a,da,2b),
	HX_("MAGENTA",09,8e,71,8e),
	HX_("CYAN",23,0d,8d,2c),
	HX_("WHITE",89,82,ab,47),
	HX_("LIGHT_BLACK",16,8a,3a,82),
	HX_("LIGHT_RED",e8,15,e6,dd),
	HX_("LIGHT_GREEN",1a,c3,35,67),
	HX_("LIGHT_YELLOW",1d,b7,b1,a2),
	HX_("LIGHT_BLUE",03,0a,df,40),
	HX_("LIGHT_MAGENTA",40,56,bd,46),
	HX_("LIGHT_CYAN",8c,0c,92,41),
	HX_("LIGHT_WHITE",00,ff,05,97),
	HX_("BG_BLACK",65,b0,3c,76),
	HX_("BG_RED",77,ba,0a,84),
	HX_("BG_GREEN",69,e9,37,5b),
	HX_("BG_YELLOW",ee,15,91,30),
	HX_("BG_BLUE",94,62,ca,fa),
	HX_("BG_MAGENTA",4f,ee,50,dc),
	HX_("BG_CYAN",1d,65,7d,fb),
	HX_("BG_WHITE",4f,25,08,8b),
	HX_("BG_LIGHT_BLACK",5c,85,56,71),
	HX_("BG_LIGHT_RED",ae,93,92,ea),
	HX_("BG_LIGHT_GREEN",60,be,51,56),
	HX_("BG_LIGHT_YELLOW",17,99,11,ec),
	HX_("BG_LIGHT_BLUE",7d,99,20,4b),
	HX_("BG_LIGHT_MAGENTA",06,2f,43,31),
	HX_("BG_LIGHT_CYAN",06,9c,d3,4b),
	HX_("BG_LIGHT_WHITE",46,fa,21,86),
	HX_("fromString",db,2d,74,54),
	::String(null())
};

void FormatFlag_Impl__obj::__register()
{
	FormatFlag_Impl__obj _hx_dummy;
	FormatFlag_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("_Console.FormatFlag_Impl_",f9,0b,64,06);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &FormatFlag_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = FormatFlag_Impl__obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(FormatFlag_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< FormatFlag_Impl__obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = FormatFlag_Impl__obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = FormatFlag_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = FormatFlag_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void FormatFlag_Impl__obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_634_boot)
HXDLIN( 634)		RESET = HX_("reset",cf,49,c8,e6);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_635_boot)
HXDLIN( 635)		BOLD = HX_("bold",85,81,1b,41);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_636_boot)
HXDLIN( 636)		ITALIC = HX_("italic",f0,2e,64,06);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_637_boot)
HXDLIN( 637)		DIM = HX_("dim",48,3d,4c,00);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_638_boot)
HXDLIN( 638)		UNDERLINE = HX_("underline",0c,15,d1,87);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_639_boot)
HXDLIN( 639)		BLINK = HX_("blink",5c,f1,f7,b4);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_640_boot)
HXDLIN( 640)		INVERT = HX_("invert",16,e7,d8,9f);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_641_boot)
HXDLIN( 641)		HIDDEN = HX_("hidden",6a,ff,95,4c);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_642_boot)
HXDLIN( 642)		BLACK = HX_("black",bf,d5,f1,b4);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_643_boot)
HXDLIN( 643)		RED = HX_("red",51,d9,56,00);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_644_boot)
HXDLIN( 644)		GREEN = HX_("green",c3,0e,ed,99);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_645_boot)
HXDLIN( 645)		YELLOW = HX_("yellow",74,9f,5c,d0);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_646_boot)
HXDLIN( 646)		BLUE = HX_("blue",9a,42,19,41);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_647_boot)
HXDLIN( 647)		MAGENTA = HX_("magenta",29,ba,9d,0e);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_648_boot)
HXDLIN( 648)		CYAN = HX_("cyan",23,45,cc,41);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_649_boot)
HXDLIN( 649)		WHITE = HX_("white",a9,4a,bd,c9);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_650_boot)
HXDLIN( 650)		LIGHT_BLACK = HX_("light_black",56,f2,92,e0);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_651_boot)
HXDLIN( 651)		LIGHT_RED = HX_("light_red",28,d2,66,cd);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_652_boot)
HXDLIN( 652)		LIGHT_GREEN = HX_("light_green",5a,2b,8e,c5);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_653_boot)
HXDLIN( 653)		LIGHT_YELLOW = HX_("light_yellow",fd,86,b4,d1);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_654_boot)
HXDLIN( 654)		LIGHT_BLUE = HX_("light_blue",e3,05,03,e2);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_655_boot)
HXDLIN( 655)		LIGHT_MAGENTA = HX_("light_magenta",80,6a,30,3a);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_656_boot)
HXDLIN( 656)		LIGHT_CYAN = HX_("light_cyan",6c,08,b6,e2);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_657_boot)
HXDLIN( 657)		LIGHT_WHITE = HX_("light_white",40,67,5e,f5);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_658_boot)
HXDLIN( 658)		BG_BLACK = HX_("bg_black",85,94,4b,51);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_659_boot)
HXDLIN( 659)		BG_RED = HX_("bg_red",97,3a,61,bc);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_660_boot)
HXDLIN( 660)		BG_GREEN = HX_("bg_green",89,cd,46,36);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_661_boot)
HXDLIN( 661)		BG_YELLOW = HX_("bg_yellow",ee,cd,89,02);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_662_boot)
HXDLIN( 662)		BG_BLUE = HX_("bg_blue",94,fe,23,0e);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_663_boot)
HXDLIN( 663)		BG_MAGENTA = HX_("bg_magenta",6f,36,f9,c3);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_664_boot)
HXDLIN( 664)		BG_CYAN = HX_("bg_cyan",1d,01,d7,0e);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_665_boot)
HXDLIN( 665)		BG_WHITE = HX_("bg_white",6f,09,17,66);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_666_boot)
HXDLIN( 666)		BG_LIGHT_BLACK = HX_("bg_light_black",9c,09,69,dd);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_667_boot)
HXDLIN( 667)		BG_LIGHT_RED = HX_("bg_light_red",ee,6b,ce,2d);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_668_boot)
HXDLIN( 668)		BG_LIGHT_GREEN = HX_("bg_light_green",a0,42,64,c2);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_669_boot)
HXDLIN( 669)		BG_LIGHT_YELLOW = HX_("bg_light_yellow",f7,cc,32,10);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_670_boot)
HXDLIN( 670)		BG_LIGHT_BLUE = HX_("bg_light_blue",5d,f9,41,dc);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_671_boot)
HXDLIN( 671)		BG_LIGHT_MAGENTA = HX_("bg_light_magenta",46,5f,2f,aa);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_672_boot)
HXDLIN( 672)		BG_LIGHT_CYAN = HX_("bg_light_cyan",e6,fb,f4,dc);
            	}
{
            	HX_STACKFRAME(&_hx_pos_58a68fd115af502b_673_boot)
HXDLIN( 673)		BG_LIGHT_WHITE = HX_("bg_light_white",86,7e,34,f2);
            	}
}

} // end namespace _Console
