// Generated by Haxe 4.2.1
#ifndef INCLUDED_markdown_Node
#define INCLUDED_markdown_Node

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(markdown,Node)
HX_DECLARE_CLASS1(markdown,NodeVisitor)

namespace markdown{


class HXCPP_CLASS_ATTRIBUTES Node_obj {
	public:
		typedef ::hx::Object super;
		HX_DO_INTERFACE_RTTI;

		void (::hx::Object :: *_hx_accept)(::Dynamic visitor); 
		static inline void accept( ::Dynamic _hx_,::Dynamic visitor) {
			(_hx_.mPtr->*( ::hx::interface_cast< ::markdown::Node_obj *>(_hx_.mPtr->_hx_getInterface(0x4834e911)))->_hx_accept)(visitor);
		}
};

} // end namespace markdown

#endif /* INCLUDED_markdown_Node */ 
